"use client";

import { useMemo, useState } from "react";

type Option = { workspaceSlug: string; workspaceName: string; companies: Array<{ id: string; name: string; cards: Array<{ id: string; label: string }> }> };

export function JoinEventForm({ token, invitationType, options }: { token: string; invitationType: "sponsor" | "exhibitor" | "speaker" | "company" | "attendee"; options: Option[] }) {
  const [workspaceSlug, setWorkspaceSlug] = useState(options[0]?.workspaceSlug ?? "");
  const workspace = options.find((item) => item.workspaceSlug === workspaceSlug);
  const [companyId, setCompanyId] = useState(workspace?.companies[0]?.id ?? "");
  const company = useMemo(() => workspace?.companies.find((item) => item.id === companyId) ?? workspace?.companies[0], [workspace, companyId]);
  const [selectedCards, setSelectedCards] = useState<string[]>(company?.cards.map((card) => card.id) ?? []);
  const [sharing, setSharing] = useState({ phone: false, email: true, website: true, location: true, socialMedia: true, productsServices: true, otherInformation: false, originalCardPreview: false });
  const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [complete, setComplete] = useState(false);
  function chooseWorkspace(value: string) { setWorkspaceSlug(value); const next = options.find((item) => item.workspaceSlug === value); const first = next?.companies[0]; setCompanyId(first?.id ?? ""); setSelectedCards(first?.cards.map((card) => card.id) ?? []); }
  function chooseCompany(value: string) { setCompanyId(value); const next = workspace?.companies.find((item) => item.id === value); setSelectedCards(next?.cards.map((card) => card.id) ?? []); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!company || !selectedCards.length || !consent) return; setBusy(true); setError(""); const response = await fetch(`/api/events/invitations/${token}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceSlug, sourceCompanyId: company.id, businessCardIds: selectedCards, participantType: invitationType, visibility: sharing, consentVersion: "event-sharing-v1" }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error || "Could not submit these cards."); return; } setComplete(true); }
  if (complete) return <div className="event-join-complete"><span>✓</span><h2>Cards sent for organizer review</h2><p>The source records remain in your workspace. Only the snapshot and fields you approved can appear in this event directory.</p><a href="/events">Browse events</a></div>;
  if (!options.length) return <div className="event-admin-empty large"><span>◇</span><h2>No verified cards are ready</h2><p>Upload and verify at least one business card in a workspace where you can share records, then return to this invitation.</p><a href="/">Open Cardwise</a></div>;
  return <form className="event-join-form" onSubmit={submit}><section><span className="eyebrow">1 · CHOOSE THE SOURCE</span><h2>Select your company and cards</h2><p>Cardwise validates that every selected card belongs to this workspace and is verified.</p><div className="event-form-grid"><label>Workspace<select value={workspaceSlug} onChange={(event) => chooseWorkspace(event.target.value)}>{options.map((option) => <option value={option.workspaceSlug} key={option.workspaceSlug}>{option.workspaceName}</option>)}</select></label><label>Company<select value={company?.id ?? ""} onChange={(event) => chooseCompany(event.target.value)}>{workspace?.companies.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><div className="event-card-picker">{company?.cards.map((card) => <label key={card.id}><input type="checkbox" checked={selectedCards.includes(card.id)} onChange={(event) => setSelectedCards((current) => event.target.checked ? [...current, card.id] : current.filter((id) => id !== card.id))} /><span><strong>{card.label}</strong><small>Verified business card</small></span></label>)}</div></section><section><span className="eyebrow">2 · CONTROL VISIBILITY</span><h2>Choose what this event can display</h2><p>Fields you turn off are removed from the public event response, not merely hidden with CSS.</p><div className="event-sharing-grid">{Object.entries(sharing).map(([key, value]) => <label key={key}><span>{key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase())}</span><input type="checkbox" checked={value} onChange={(event) => setSharing((current) => ({ ...current, [key]: event.target.checked }))} /></label>)}</div></section><label className="event-consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span><strong>I am authorized to share these cards for this event.</strong><small>I understand that the organizer will receive a controlled snapshot, can approve or reject it, and that the submission can later be withdrawn.</small></span></label>{error && <p className="event-form-error" role="alert">{error}</p>}<button className="event-join-submit" disabled={busy || !consent || !selectedCards.length}>{busy ? "Submitting securely…" : `Submit ${selectedCards.length} card${selectedCards.length === 1 ? "" : "s"} for review`}</button></form>;
}
