import { count, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { aiGenerations, businessCards, users, workspaceSubscriptions, workspaces } from "@/db/schema";
import { requirePlatformStaff } from "@/lib/auth/superadmin";

export const dynamic = "force-dynamic";

export default async function SuperadminPage() {
  const staff = await requirePlatformStaff();
  if (!process.env.DATABASE_URL) return <main className="page-shell admin-dashboard"><div className="page-title-row"><div><span className="eyebrow">PLATFORM CONTROL PLANE</span><h1>Cardwise superadmin</h1><p>Your Clerk account has superadmin access. Connect the application database to load live tenant, billing, AI, and moderation data.</p></div><span className="status-review">{staff.role}</span></div><section className="stats-grid"><div className="stat-card"><span className="stat-icon coral">◇</span><div><strong>0</strong><span>Workspaces</span></div></div><div className="stat-card"><span className="stat-icon navy">◎</span><div><strong>0</strong><span>Users</span></div></div><div className="stat-card"><span className="stat-icon green">▣</span><div><strong>0</strong><span>Cards</span></div></div><div className="stat-card"><span className="stat-icon ochre">!</span><div><strong>0</strong><span>AI failures</span></div></div></section><section className="admin-panel"><div className="section-head compact"><div><span className="eyebrow">DATABASE SETUP</span><h2>Live operations are waiting for DATABASE_URL</h2></div></div><p className="admin-setup-copy">The access check is active for this Clerk user. Add the pooled Postgres connection string after applying the Cardwise schema to enable platform reports and event moderation.</p></section></main>;
  const db = getDb();
  const [[workspaceCount], [userCount], [cardCount], [failedGenerationCount], recentWorkspaces] = await Promise.all([
    db.select({ value: count() }).from(workspaces), db.select({ value: count() }).from(users), db.select({ value: count() }).from(businessCards), db.select({ value: count() }).from(aiGenerations).where(eq(aiGenerations.status, "failed")),
    db.select({ id: workspaces.id, name: workspaces.name, slug: workspaces.slug, type: workspaces.type, status: workspaces.status, createdAt: workspaces.createdAt, plan: workspaceSubscriptions.planKey, subscriptionStatus: workspaceSubscriptions.status }).from(workspaces).leftJoin(workspaceSubscriptions, eq(workspaceSubscriptions.workspaceId, workspaces.id)).orderBy(desc(workspaces.createdAt)).limit(50),
  ]);
  return <main className="page-shell admin-dashboard"><div className="page-title-row"><div><span className="eyebrow">PLATFORM CONTROL PLANE</span><h1>Cardwise superadmin</h1><p>Global operations, tenant health, subscriptions, AI failures, and abuse response.</p></div><span className="status-review">{staff.role}</span></div><section className="stats-grid"><div className="stat-card"><span className="stat-icon coral">◇</span><div><strong>{workspaceCount.value}</strong><span>Workspaces</span></div></div><div className="stat-card"><span className="stat-icon navy">◎</span><div><strong>{userCount.value}</strong><span>Users</span></div></div><div className="stat-card"><span className="stat-icon green">▣</span><div><strong>{cardCount.value}</strong><span>Cards</span></div></div><div className="stat-card"><span className="stat-icon ochre">!</span><div><strong>{failedGenerationCount.value}</strong><span>AI failures</span></div></div></section><section className="admin-panel"><div className="section-head compact"><div><span className="eyebrow">TENANT OPERATIONS</span><h2>Recent workspaces</h2></div></div><div className="superadmin-table"><div className="superadmin-row head"><span>Workspace</span><span>Type</span><span>Plan</span><span>Status</span><span>Created</span></div>{recentWorkspaces.map((workspace) => <div className="superadmin-row" key={workspace.id}><span><strong>{workspace.name}</strong><small>{workspace.slug}</small></span><span>{workspace.type}</span><span>{workspace.plan ?? "free"}</span><span>{workspace.subscriptionStatus ?? workspace.status}</span><span>{workspace.createdAt.toLocaleDateString()}</span></div>)}</div></section></main>;
}
