import Link from "next/link";
import { notFound } from "next/navigation";
import { PromotionCheckoutButton } from "@/components/events/promotion-checkout-button";
import { getWorkspaceEvent } from "@/lib/repositories/events";
import { listPromotionPackages } from "@/lib/events/promotions";

export const dynamic = "force-dynamic";

export default async function EventPromotionPage({ params, searchParams }: { params: Promise<{ workspaceSlug: string; eventId: string }>; searchParams: Promise<{ payment?: string }> }) { const { workspaceSlug, eventId } = await params; const [event, packages] = await Promise.all([getWorkspaceEvent(workspaceSlug, eventId), listPromotionPackages()]); if (!event) notFound(); const { payment } = await searchParams; return <main className="event-admin-page"><div className="event-admin-nav"><Link href={`/app/${workspaceSlug}/events/${eventId}`}>← Manage event</Link><span>Paid promotion</span></div><div className="event-admin-heading"><div><span className="eyebrow">GROW EVENT DISCOVERY</span><h1>Promote {event.title}</h1><p>Pay for transparent, clearly labeled placement. Payment does not guarantee platform approval; rejected campaigns can be refunded by a platform administrator.</p></div></div>{payment === "success" && <div className="event-payment-notice success">Payment received. Your promotion is queued for platform review.</div>}{payment === "cancelled" && <div className="event-payment-notice">Checkout was cancelled. No promotion was activated.</div>}<div className="promotion-package-grid">{packages.map((item) => <article key={item.id}><span className="participant-chip">{item.durationDays} days</span><h2>{item.name}</h2><p>{item.description}</p><strong>{new Intl.NumberFormat("en-US", { style: "currency", currency: item.currency.toUpperCase() }).format(item.priceCents / 100)}</strong><ul><li>Clearly marked sponsored placement</li><li>Event engagement analytics</li><li>Platform moderation before activation</li></ul><PromotionCheckoutButton workspaceSlug={workspaceSlug} eventId={eventId} packageId={item.id} /></article>)}</div></main>; }
