import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { eventPromotionOrders, eventPromotionPackages, events } from "@/db/schema";
import { SuperadminEventControls } from "@/components/events/superadmin-event-controls";
import { requirePlatformStaff } from "@/lib/auth/superadmin";

export const dynamic = "force-dynamic";

export default async function SuperadminEventsPage() { await requirePlatformStaff("events:moderate"); const db = getDb(); const [pendingEvents, promotions] = await Promise.all([db.select().from(events).where(eq(events.moderationStatus, "pending")).orderBy(desc(events.createdAt)), db.select({ order: eventPromotionOrders, eventTitle: events.title, packageName: eventPromotionPackages.name }).from(eventPromotionOrders).innerJoin(events, eq(events.id, eventPromotionOrders.eventId)).innerJoin(eventPromotionPackages, eq(eventPromotionPackages.id, eventPromotionOrders.packageId)).where(eq(eventPromotionOrders.status, "paid_pending_review")).orderBy(desc(eventPromotionOrders.createdAt))]); return <main className="event-admin-page"><div className="event-admin-nav"><Link href="/superadmin">← Platform dashboard</Link><span>Trust and monetization</span></div><div className="event-admin-heading"><div><span className="eyebrow">PLATFORM MODERATION</span><h1>Events and promotions</h1><p>Review marketplace content separately from paid placement. Payment never bypasses moderation.</p></div></div><div className="superadmin-event-grid"><section className="event-admin-panel"><div className="event-panel-heading"><div><span className="eyebrow">EVENT LISTINGS</span><h2>Awaiting review</h2></div><span>{pendingEvents.length}</span></div>{pendingEvents.map((event) => <article key={event.id}><div><span className="participant-chip">{event.category || event.eventType}</span><h3>{event.title}</h3><p>{event.summary}</p><small>{event.startsAt.toLocaleString()} · {[event.venueName, event.city].filter(Boolean).join(", ")}</small></div><SuperadminEventControls endpoint={`/api/superadmin/events/${event.id}/moderate`} /></article>)}{!pendingEvents.length && <div className="event-admin-empty"><h3>Queue is clear</h3></div>}</section><section className="event-admin-panel"><div className="event-panel-heading"><div><span className="eyebrow">PAID PLACEMENT</span><h2>Promotion review</h2></div><span>{promotions.length}</span></div>{promotions.map(({ order, eventTitle, packageName }) => <article key={order.id}><div><span className="participant-chip">{packageName}</span><h3>{eventTitle}</h3><p>{new Intl.NumberFormat("en-US", { style: "currency", currency: order.currency.toUpperCase() }).format(order.amountCents / 100)} paid · activation pending</p></div><SuperadminEventControls endpoint={`/api/superadmin/event-promotions/${order.id}/moderate`} /></article>)}{!promotions.length && <div className="event-admin-empty"><h3>No paid promotions waiting</h3></div>}</section></div></main>; }
