import Link from "next/link";
import { listWorkspaceEvents } from "@/lib/repositories/events";

export const dynamic = "force-dynamic";

export default async function WorkspaceEventsPage({ params }: { params: Promise<{ workspaceSlug: string }> }) {
  const { workspaceSlug } = await params;
  const events = await listWorkspaceEvents(workspaceSlug);
  return <main className="event-admin-page"><div className="event-admin-nav"><Link href={`/app/${workspaceSlug}`}>← Back to directory</Link><span>Event organizer</span></div><div className="event-admin-heading"><div><span className="eyebrow">YOUR EVENT WORKSPACE</span><h1>Networking events</h1><p>Create an event, invite companies to share selected cards, moderate the directory, and measure engagement.</p><div className="workspace-event-heading-links"><Link href={`/app/${workspaceSlug}/events/participating`}>Cards your team shared</Link><Link href="/events">Browse public events</Link></div></div><Link href={`/app/${workspaceSlug}/events/new`}>＋ Create event</Link></div><div className="event-admin-stats"><div><strong>{events.length}</strong><span>Total events</span></div><div><strong>{events.filter((event) => event.status === "scheduled").length}</strong><span>Upcoming</span></div><div><strong>{events.filter((event) => event.moderationStatus === "pending").length}</strong><span>Awaiting platform review</span></div><div><strong>{events.filter((event) => event.status === "completed").length}</strong><span>Past directories</span></div></div>{events.length ? <div className="workspace-event-list">{events.map((event) => <article key={event.id}><div className="workspace-event-date"><span>{event.startsAt.toLocaleDateString("en-UG", { month: "short" })}</span><strong>{event.startsAt.getDate()}</strong></div><div><span className="participant-chip">{event.moderationStatus.replaceAll("_", " ")}</span><h2>{event.title}</h2><p>{[event.venueName, event.city, event.country].filter(Boolean).join(", ")} · {event.startsAt.toLocaleDateString()}</p></div><div className="workspace-event-actions"><Link href={`/app/${workspaceSlug}/events/${event.id}`}>Manage</Link>{event.moderationStatus === "approved" && <Link className="outline" href={`/events/${event.slug}`}>View public page</Link>}</div></article>)}</div> : <div className="event-admin-empty large"><span>◇</span><h2>Create your first networking event</h2><p>Cardwise will give you a public listing, a consent-based attendee card directory, secure company invitation links, and engagement analytics.</p><Link href={`/app/${workspaceSlug}/events/new`}>Create event draft</Link></div>}</main>;
}
